config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'admin/sold_teapots', to: 'teapots#sold_index', as: 'sold_teapots'
  resources :teapots
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :checkouts, only: :show
  resources :payments, only: :show

  resources :cart_items, only: [:index, :create, :destroy] do
    collection do
      get :total_price
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "teapots#index"
end

app/models/teapot.rb
require 'money'
class Teapot < ApplicationRecord
  has_many_attached :images
  monetize :price_cents
  has_one :cart_item, dependent: :destroy
  has_one :order_item, dependent: :destroy

  validates :sku, presence: true, uniqueness: true
  validates :maker, presence: true
  validates :price_cents, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :kilntype, presence: true
  validates :shape, presence: true
  # validates :height, :width, :depth, :weight, :ccs, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # uncomment line above if dimensions need to be made mandatory for some reason.

  def formatted_price
    Money.new(self.price, "JPY").format
  end

end

app/controllers/teapots_controller.rb
class TeapotsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize_teapot, only: [:new, :create, :edit, :update, :destroy]

  def index
    teapots_scope = Teapot.where(in_stock: true)

    @makers = teapots_scope.distinct.pluck(:maker)
    @styles = teapots_scope.distinct.pluck(:shape)
    @materials = teapots_scope.distinct.pluck(:kilntype)

    # Sort the teapots based on the search criteria
    if params[:search_by].present?
      case params[:search_by]
      when 'price'
        condition = params[:price_condition] == 'less_than' ? '<=' : '>='
        teapots_scope = teapots_scope.where("price_cents #{condition} ?", params[:price].to_i)
      when 'maker'
        teapots_scope = teapots_scope.where(maker: params[:maker])
      when 'style'
        teapots_scope = teapots_scope.where(shape: params[:style])
      when 'material'
        teapots_scope = teapots_scope.where(kilntype: params[:material])
      when 'capacity'
        condition = params[:capacity_condition] == 'less_than' ? '<=' : '>='
        teapots_scope = teapots_scope.where("ccs #{condition} ?", params[:capacity].to_i)
      end
    end

    # Order the teapots by price in ascending order for the main display
    @pagy, @teapots = pagy(teapots_scope.order(price_cents: :asc), items: 24)

    # Get the top 6 most popular teapots based on views for the carousel
    @most_popular = Teapot.where(in_stock: true).order(views: :desc).limit(6)
  end

  def sold_index
    @pagy, @sold_teapots = pagy(Teapot.where(in_stock: false).order(created_at: :desc), items: 24)
  end

  def show
    @teapot = Teapot.find(params[:id])
    @teapot.increment!(:views)
  end

  def new
    @teapot = Teapot.new
    authorize @teapot
  end

  def create
    @teapot = Teapot.new(teapot_params)
    authorize @teapot

    if @teapot.save
      flash[:notice] = 'Teapot was successfully created.'
      redirect_to new_teapot_path
    else
      flash.now[:alert] = 'There was an error creating the teapot. Please check the form for errors.'
      Rails.logger.debug "Flash alert set: #{flash.now[:alert]}"
      render :new
    end
  end

  def edit
    @teapot = Teapot.find(params[:id])
    authorize @teapot
  end

  def update
    @teapot = Teapot.find(params[:id])
    authorize @teapot

    # Handle removal of selected images
    if params[:teapot][:remove_images].present?
      params[:teapot][:remove_images].each do |signed_id|
        attachment = @teapot.images.attachments.find { |att| att.signed_id == signed_id }
        if attachment
          Rails.logger.debug "Purging image with signed_id: #{signed_id}"
          attachment.purge
        else
          Rails.logger.debug "No image found with signed_id: #{signed_id}"
        end
      end
    end

    # Update the teapot with other attributes (excluding images)
    if @teapot.update(teapot_params.except(:images))
      # Attach new images if any
      if params[:teapot][:images].present?
        @teapot.images.attach(params[:teapot][:images])
      end

      flash[:notice] = 'Teapot was successfully updated.'
      redirect_to teapot_path(@teapot)
    else
      flash.now[:alert] = 'There was an error updating the teapot.'
      render :edit
    end
  end

  def destroy
    @teapot = Teapot.find(params[:id])
    authorize @teapot

    if @teapot.destroy
      flash[:notice] = 'Teapot was successfully deleted.'
    else
      flash[:alert] = 'There was an error deleting the teapot.'
    end

    respond_to do |format|
      format.html { redirect_to teapots_path }
      format.json { head :no_content }
    end
  end

  private

  def authorize_teapot
    authorize @teapot || Teapot
  end

  def teapot_params
    params.require(:teapot).permit(:height, :width, :depth, :weight, :ccs, :comment, :price_cents, :kilntype, :shape, :maker, :views, :in_stock, :sku, images: [])
  end

  def authorize_admin
    redirect_to root_path, alert: "Not authorized." unless current_user.admin?
  end
end

app/helpers/teapots_helper.rb
module TeapotsHelper
  include Pagy::Frontend
end

app/views/teapots/edit.html.erb
<section>
  <div class="container">
    <h1 class="section-title">Edit Details</h1>
      <%= simple_form_for @teapot, html: { multipart: true, class: "edit-form" } do |f| %>
        <div class="text-inputs">
          <h1>Teapot Info</h1>
          <%= f.input :height, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :width, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :depth, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :weight, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :ccs, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :comment, as: :text %>
          <%= f.input :price_cents, required: true, input_html: { min: 0, step: 1, type: 'number' } %>
          <%= f.input :kilntype, required: true %>
          <%= f.input :shape, required: true %>
          <%= f.input :maker, required: true %>
          <%= f.input :sku, required: true %>
        </div>


        <div class="current-images-block">
          <h1>Current Images</h1>
          <div class="current-images">
            <% @teapot.images.each_with_index do |image, index| %>
              <div class="image-thumbnail">
                <%= cl_image_tag(image.key, alt: "Teapot Image", class: "thumbnail", width: 150, height: 150, crop: :fill) %>
                <div class="remove-checkbox">
                  <%= check_box_tag "teapot[remove_images][]", image.signed_id %>
                  <label>Check to remove</label>
                </div>
              </div>
            <% end %>
          </div>
          <h1>Add New Images</h1>
          <%= f.input :images, as: :file, input_html: { multiple: true } %>
          <div class="form-submit">
            <%= f.button :submit, "Save Changes", class: "action-button" %>
          </div>
        </div>
      <% end %>
  </div>
</section>

app/views/teapots/index.html.erb
<section>
  <div class="container">
    <h1 class="section-title">Most Popular</h1>
    <div class="carousel">
      <input type="radio" name="slides" checked="checked" id="slide-1">
      <input type="radio" name="slides" id="slide-2">
      <input type="radio" name="slides" id="slide-3">
      <input type="radio" name="slides" id="slide-4">
      <input type="radio" name="slides" id="slide-5">
      <input type="radio" name="slides" id="slide-6">
      <ul class="carousel__slides">
        <% @most_popular.each do |teapot| %>
          <li class="carousel__slide">
            <figure>
              <div>
                <% if teapot.images.attached? %>
                  <%= cl_image_tag(teapot.images.first.key, width: 300, height: 300, crop: :fill) %>
                <% end %>
              </div>
              <figcaption>
                <h1><%= humanized_money_with_symbol(teapot.price) %></h1>
                <%= teapot.comment %>
                <span class="maker">Artist: <%= teapot.maker %></span>
              </figcaption>
            </figure>
          </li>
        <% end %>
      </ul>
      <ul class="carousel__thumbnails">
        <% @most_popular.each_with_index do |teapot, index| %>
          <li>
            <label for="slide-<%= index + 1 %>"><%= cl_image_tag(teapot.images.first.key, width: 150, height: 150, crop: :fill) %></label>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="section-spacer">
  </div>
  <div class="container">
    <h1 class="section-title">Collection</h1>
    <div style="display: flex; justify-content: center">
      <%= form_with url: teapots_path, method: :get, local: true, class: "search-form", data: { controller: "search", search_makers_value: @makers.to_json, search_styles_value: @styles.to_json, search_materials_value: @materials.to_json } do |f| %>
        <div class="search-by-options">
          <label>Search by:</label>
          <%= f.radio_button :search_by, 'price', checked: true, data: { action: "input->search#updateForm" } %> Price
          <%= f.radio_button :search_by, 'maker', data: { action: "input->search#updateForm" } %> Maker
          <%= f.radio_button :search_by, 'style', data: { action: "input->search#updateForm" } %> Style
          <%= f.radio_button :search_by, 'material', data: { action: "input->search#updateForm" } %> Material
          <%= f.radio_button :search_by, 'capacity', data: { action: "input->search#updateForm" } %> Capacity
        </div>
        <div class="search-by-dropdowns">
          <div id="search-input-container" data-search-target="inputContainer">
            <!-- This will be dynamically updated by JavaScript based on the selected search_by option -->
          </div>
          <%= f.submit "Search", class: "action-button" %>
        </div>
      <% end %>
    </div>
    <div class="all-teapots-container">
      <% @teapots.each_with_index do |teapot, teapot_index| %>
        <%= link_to teapot_path(teapot), class: "teapot-link" do %>
          <div class="teapot-card-simple">
            <div  class="teapot-slides" data-controller="teapot-slides" data-action="mouseenter->teapot-slides#startSlideshow mouseleave->teapot-slides#stopSlideshow">
              <% teapot.images.each_with_index do |image, image_index| %>
                <% if image_index == 0 %>
                  <% key = teapot.images[image_index].key %>
                  <%= cl_image_tag(key, alt: "Teapot Image", class: "teapot-image", id: "slide-#{teapot_index + 1}-#{image_index + 1}", width: 300, height: 300, crop: :fill, data: { 'teapot-slides-target': 'slide' }) %>
                <% else %>
                  <% key = teapot.images[image_index].key %>
                  <%= cl_image_tag(key, alt: "Teapot Image", class: "teapot-image-hidden", id: "slide-#{teapot_index + 1}-#{image_index + 1}", width: 300, height: 300, crop: :fill, data: { 'teapot-slides-target': 'slide' }) %>
                <% end %>
              <% end %>
            </div>
            <div class="card-info-container">
              <p class="teapot-price-text"><%= humanized_money_with_symbol(teapot.price) %></p>
              <p class="teapot-maker-text"><strong><%= teapot.maker %></strong></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <h2 class="paginator"><%= pagy_nav(@pagy).html_safe %></h2>
  </div>
</section>

app/views/teapots/new.html.erb
<section>
  <div class="container">
    <h1 class="section-title">New Teapot</h1>
    <%= simple_form_for @teapot, html: { multipart: true, data: { turbo: false }, class: "new-teapot-form"} do |f| %>
      <%= f.error_notification %>
      <div class="text-inputs">
        <h1>Enter Info</h1>
        <%= f.input :height, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :width, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :depth, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :weight, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :ccs, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :comment, as: :text %>
        <%= f.input :price_cents, input_html: { min: 0, step: 1, type: 'number' } %>
        <%= f.input :kilntype %>
        <%= f.input :shape %>
        <%= f.input :maker %>
        <%= f.input :sku %>
        <%= f.input :images, as: :file, input_html: { multiple: true } %>
        <div class="form-submit">
          <%= f.button :submit, "Create Teapot", class: "action-button" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/teapots/show.html.erb
<section>
  <div class="container">
    <h1 class="section-title"><%= @teapot.maker %></h1>
    <div class="teapot-card">
      <div>
        <div class="carousel-two">
          <% @teapot.images.each_with_index do |image, index| %>
            <% if index == 0 %>
              <input type="radio" name="slides" checked="checked" id="slide-1">
            <% else %>
              <input type="radio" name="slides" id="slide-<%= index + 1 %>">
            <% end %>
          <% end %>
          <ul class="carousel_two__slides">
            <% @teapot.images.each do |image| %>
              <li class="carousel_two__slide">
                <figure>
                  <div>
                    <%= cl_image_tag(image.key, width: 500, height: 500, crop: :fill) %>
                  </div>
                </figure>
              </li>
            <% end %>
          </ul>
          <ul class="carousel_two__thumbnails">
            <% @teapot.images.each_with_index do |image, index| %>
              <li>
                <label for="slide-<%= index + 1 %>"><%= cl_image_tag(image.key, width: 68, height: 68, crop: :fill) %></label>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="card-info-container">
        <div class="visual-info-boxes-container">
          <div class="dimension-box">
            <%= image_tag "dimensions.png" %>
            <p class="teapot-height-text"><%= @teapot.height / 10.to_f %> cm</p>
            <p class="teapot-width-text"><%= @teapot.width / 10.to_f %> cm</p>
            <p class="teapot-depth-text"><%= @teapot.depth / 10.to_f %> cm</p>
          </div>
          <div class="capacity-box"><%= image_tag "capacity.png" %>
            <p class="teapot-ccs-text"><%= @teapot.ccs %> cc</p>
          </div>
          <div class="weight-box"><%= image_tag "weight.png" %>
            <p class="teapot-weight-text"><%= @teapot.weight %> g</p>
          </div>
          <div class="teapot-type-info">
            <p>Shape: <%= @teapot.shape %></p>
            <p>Firing: <%= @teapot.kilntype %></p>
          </div>
        </div>
        <div class="teapot-info-lower-half">
          <div class="comment-box">
            <p><%= @teapot.comment %></p>
          </div>
          <div class="text-only-info-container">
            <p class="teapot-price-text"><%= @teapot.formatted_price %></p>
          </div>
          <% if user_signed_in? %>
            <% if current_user.cart && (cart_item = current_user.cart.cart_items.find_by(teapot_id: @teapot.id)) %>
              <%= form_with(url: cart_item_path(cart_item), method: :delete, data: { controller: "remove-from-cart" }) do %>
                <%= hidden_field_tag 'teapot_id', @teapot.id %>
                <%= hidden_field_tag 'cart_item_id', cart_item.id %>
                <%= submit_tag 'Remove from Cart', class: 'stretchy-action-button', data: { action: "click->remove-from-cart#remove" } %>
              <% end %>
            <% else %>
              <%= form_with(url: cart_items_path, method: :post, data: { controller: "add-to-cart" }) do %>
                <%= hidden_field_tag 'teapot_id', @teapot.id %>
                <%= submit_tag 'Add to Cart', class: 'stretchy-action-button', data: { action: "click->add-to-cart#add" } %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to 'Log In', new_user_session_path, class: 'stretchy-action-button' %>
            <p class="stretchy-button-label">(You must be logged in to make purchases.)</p>
          <% end %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'Edit Details', edit_teapot_path(@teapot), type: 'button', class: 'stretchy-action-button' %>
            <%= button_tag 'Delete Teapot', type: 'button', class: 'stretchy-action-button', data: { controller: 'delete', action: 'click->delete#confirm', delete_teapot_id_value: @teapot.id } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/teapots/sold_index.html.erb
<section>
  <div class="container">
    <h1 class="section-title">Sold Teapots</h1>
    <div class="all-teapots-container">
      <% @sold_teapots.each_with_index do |teapot, teapot_index| %>
        <%= link_to teapot_path(teapot), class: "teapot-link" do %>
          <div class="teapot-card-simple">
            <div class="sold-image-container">
              <% if teapot.images.attached? %>
                <%= cl_image_tag(teapot.images.first.key, alt: "Teapot Image", class: "teapot-image", width: 300, height: 300, crop: :fill) %>
              <% end %>
            </div>
            <div class="card-info-container">
              <p class="teapot-price-text"><%= humanized_money_with_symbol(teapot.price) %></p>
              <p class="teapot-maker-text"><strong><%= teapot.maker %></strong></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <h2 class="paginator"><%= pagy_nav(@pagy).html_safe %></h2>
  </div>
</section>