config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'admin/sold_teapots', to: 'teapots#sold_index', as: 'sold_teapots'
  resources :teapots
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :checkouts, only: :show
  resources :payments, only: :show

  resources :cart_items, only: [:index, :create, :destroy] do
    collection do
      get :total_price
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "teapots#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :teapot
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cart = current_user.cart
    @cart_items = current_user.cart.cart_items.includes(:teapot)
  end

  def create
    @teapot = Teapot.find(params[:teapot_id])
    @cart = current_user.cart

    if @cart.teapots.include?(@teapot)
      respond_to do |format|
        format.html { redirect_to @teapot, notice: "This teapot is already in your cart." }
        format.json { render json: { message: "This teapot is already in your cart." }, status: :unprocessable_entity }
      end
    else
      @cart_item = @cart.cart_items.build(teapot: @teapot)

      if @cart_item.save
        respond_to do |format|
          format.html { redirect_to @teapot, notice: "Teapot successfully added to your cart." }
          format.json { render json: { message: "Teapot successfully added to your cart.", cart_item_id: @cart_item.id }, status: :created }
        end
      else
        respond_to do |format|
          format.html { redirect_to @teapot, alert: "Failed to add teapot to your cart." }
          format.json { render json: { message: "Failed to add teapot to your cart." }, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @cart_item = current_user.cart.cart_items.find(params[:id])

    if @cart_item
      @cart_item.destroy
      respond_to do |format|
        format.html { redirect_to teapot_path(params[:teapot_id]), notice: "Teapot removed from your cart." }
        format.json { render json: { message: "Teapot removed from your cart." }, status: :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to teapot_path(params[:teapot_id]), alert: "Teapot not found in your cart." }
        format.json { render json: { message: "Teapot not found in your cart." }, status: :not_found }
      end
    end
  end

  def total_price
    begin
      if current_user.cart && current_user.cart.cart_items
        total_price_cents = current_user.cart.cart_items.joins(:teapot).sum('teapots.price_cents')
        formatted_price = Money.new(total_price_cents, "JPY").format
        render json: { total_price: formatted_price }
      else
        render json: { error: "Cart or cart items not found" }, status: :internal_server_error
      end
    rescue => e
      Rails.logger.error "Error calculating total price: #{e.message}"
      Rails.logger.error e.backtrace.join("\n")
      render json: { error: "Error calculating total price" }, status: :internal_server_error
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<section>
  <div class="container" data-controller="cart-page-item-remove">
    <h1 class="section-title">Your Cart</h1>
    <% if @cart_items.any? %>
      <ul class="cart-items-list">
        <% @cart_items.each do |cart_item| %>
          <li class="cart-item">
            <%= cl_image_tag(cart_item.teapot.images.first.key, width: 100, height: 100, crop: :fill) %>
            <div class="item-details">
              <p><%= cart_item.teapot.maker %></p>
              <p>SKU: <%= cart_item.teapot.sku %></p>
            </div>
            <div class="item-price">
              <p><%= Money.new(cart_item.teapot.price_cents, "JPY").format %></p>
            </div>
            <%= form_with(url: cart_item_path(cart_item), data: { "turbo-method": :delete }, data: { action: "click->cart-page-item-remove#remove" }, class: "remove-button") do |form| %>
              <%= hidden_field_tag 'teapot_id', cart_item.teapot.id %>
              <%= hidden_field_tag 'cart_item_id', cart_item.id %>
              <%= submit_tag 'Remove', class: 'remove-item-button' %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div class="total-price" data-cart-page-item-remove-target="totalPrice">
        <p class="total-price">Total: <%= Money.new(@cart_items.sum { |item| item.teapot.price_cents }, "JPY").format %></p>
      </div>
      <%= link_to "Proceed to Checkout", checkout_path(id: @cart) %>
    <% else %>
      <p>Your cart is empty.</p>
    <% end %>
  </div>
</section>