config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'admin/sold_teapots', to: 'teapots#sold_index', as: 'sold_teapots'
  resources :teapots
  resources :orders, only: [:show, :create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :checkouts, only: :show
  resources :payments, only: :show

  resources :cart_items, only: [:index, :create, :destroy] do
    collection do
      get :total_price
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "teapots#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shinkouen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'pagy' %>
    <%= stylesheet_link_tag 'pagy' %>
  </head>

  <body class="black-wallpaper">
    <div class="navbar">
      <%= image_tag "shinkouen_logo_off_white.png" %>
      <div class="store-name-container">
        <h1 id="japanese-navbar-name">新香園茶舗</h1>
        <h3>Shinkouen Tea House</h3>
      </div>
      <div class="horizontal-spacer"></div>
      <div class="navbar-button-container">
        <ul class="nav-list">
          <li class="nav-item active">
            <%= link_to "Teapots", teapots_path %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "My Cart", cart_items_path %>
            </li>
          <% end %>
          <li class="nav-item">
            About Us
          </li>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to "Add New Teapot", new_teapot_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Sold", sold_teapots_path %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="medium-white-line"></div>
    <div class="thin-white-line"></div>
    <div class="flash-container">
      <% flash.each do |type, message| %>
        <div class="flash <%= type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>